version: '3'

services:
  bot:
    build: .
    volumes:
      - "./data.db:/app/data.db"
    ports:
      - "8080:80"
      - "8443:443"
    command: ["python3", "main.py"]

  cronos:
    build: .
    volumes:
      - "./data.db:/app/data.db"
    ports:
      - "80:80"
      - "443:443"
    command: ["python3", "cron.py"]
